version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  install-dependencies:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install --prefer-offline --no-progress
      - save_cache:
          paths:
            - node_modules
          key: v3-dependencies-{{ checksum "package.json" }}
      - persist-to-workspace
  lint:
    executor: node
    steps:
      - attach-workspace
      - run:
          name: Check formatting
          command: yarn lint
  audit:
    executor: node
    steps:
      - attach-workspace
      - run:
          name: Audit package dependencies
          command: yarn audit-ci
  build:
    executor: node
    steps:
      - attach-workspace
      - run:
          name: Build project
          command: yarn build
      - persist-to-workspace
  test:
    executor: node-postgres
    parallelism: 6
    resource_class: large
    steps:
      - attach-workspace
      - download-code-climate-test-reporter
      - run:
          name: Wait for postgres db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - setup-jest-junit-env-variables
      - run:
          name: Run database migrations
          command: node ./node_modules/typeorm/cli.js migration:run
      - run:
          name: Run tests
          command: |
            TEST_FILES_NAME=$(circleci tests glob "src/**/*.spec.ts" | circleci tests split --split-by=filesize)
            node ./node_modules/jest/bin/jest.js $TEST_FILES_NAME --coverage --reporters=default --reporters=jest-junit --runInBand --forceExit
      - store_test_results:
          path: tmp/test-results/
      - persist-code-coverage-to-workspace:
          fileName: codeclimate.non-taxonomy$CIRCLE_NODE_INDEX.json
  upload-code-coverage:
    executor: node
    steps:
      - attach-code-coverage-workspace
      - download-code-climate-test-reporter
      - run:
          name: Push Test coverage to Codeclimate
          command: |
            ./tmp/cc-test-reporter sum-coverage tmp/coverage/codeclimate.*.json -p 7 -o tmp/coverage/codeclimate.total.json
            ./tmp/cc-test-reporter upload-coverage -i tmp/coverage/codeclimate.total.json
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-deploy:
    jobs:
      - install-dependencies
      - audit:
          requires:
            - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - build:
          requires:
            - install-dependencies
      - test:
          requires:
            - build
            - audit
            - lint
      - upload-code-coverage:
          requires:
            - test
